### ISSUE TITLE
Kindly update to swift 3. 

### ISSUE THREAD

**Issue by NasrullahKhan** [devedbox/AXBadgeView-Swift#1]

**Comment by devedbox** [comment]
Sorry for taking so long to reply u. Updating to swift 3.0 will be ready in a moment.

**Comment by devedbox** [comment]
Now try the release [v0.2.0](https://github.com/devedbox/AXBadgeView-Swift/releases/tag/0.2.0). `v0.2.0` has already updated to `swift3.0`.
